# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160419_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=b'media/', verbose_name=b'Image'),
        ),
    ]
