# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160421_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
